AllCops:
  EnabledByDefault: true
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'vendor/**/*'

Bundler/OrderedGems:
  TreatCommentsAsGroupSeparators: false

Fairmoney/NoIfInTestDescriptions:
  Description: 'Test descriptions should not include "if", use "when" instead'
  Enabled: true
  VersionAdded: '0.91'

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/LineLength:
  Max: 149

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
  IndentationWidth: 2

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Metrics/BlockLength:
  Exclude:
    - 'config/environments/*.rb'
    - 'config/routes.rb'
    - 'db/migrate/*_init_schema.rb'
  IgnoredMethods:
    - 'describe'
    - 'context'

Naming/VariableNumber:
  EnforcedStyle: snake_case

RSpec/DescribedClass:
  EnforcedStyle: explicit

RSpec/MessageExpectation:
  Enabled: false

RSpec/MessageSpies:
  EnforcedStyle: receive

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  Exclude:
    - 'config/application.rb'

Style/Copyright:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DocumentationMethod:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/MethodCallWithArgsParentheses:
  Enabled: true
  Exclude:
    - 'db/migrate/*'
  IgnoredMethods:
    - gem
    - ruby
    - require
    - require_relative
    - source
    - run
    - load_defaults
    - raise
    - throw
    - render
    - redirect_to
    - head
    - layout
    - yield
    - define
    - describe
    - to
    - to_not
    - not_to
    - and_return
    - puts
    - get
    - put
    - post

Style/MissingElse:
  Enabled: false

Style/StringHashKeys:
  Exclude:
    - 'config/routes.rb'
